home/urls.py
from django.urls import path
from home import views

app_name = 'home'

urlpatterns = [
    path('home/', views.PropertiesView.as_view(), name='home'),
    path('contact/', views.contact, name='contact'),
    path('detail/<slug:slug>/', views.PropertyDetailViews.as_view(), name='detail'),

]

properties/urls.py
from django.urls import path
from . import views

app_name = 'properties'
urlpatterns = [
    path('propertie/<int:category_id>', views.PropertiesByCategoryView.as_view(), name='products'),
    path('visit/', views.VisitCreateView.as_view(), name='visit'),
    path('property/all/', views.PropertiesView.as_view(), name='property_list')
]

villaNova/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('properties.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.template.defaultfilters import length, slugify


class Category(models.Model):
    about = models.TextField()
    title = models.CharField(max_length=20)
    active = models.BooleanField(default=True)
    img = models.ImageField(upload_to='Category/')

    def __str__(self):
        return self.title


class SingleProperty(models.Model):
    total = models.IntegerField()
    payment = models.CharField(max_length=15)
    safety = models.CharField(max_length=15)
    contract = models.CharField(max_length=100)
    active_parking = models.BooleanField(default=True)


class Properties(models.Model):
    about = models.TextField(verbose_name='درباره دسته')
    description = models.TextField(verbose_name='توضیحات')
    title = models.CharField(max_length=100, unique=True,verbose_name='عنوان')
    price = models.IntegerField(verbose_name='قیمت')
    image = models.ImageField(upload_to='properties/',verbose_name='عکس')
    bathroom = models.CharField(max_length=30,verbose_name='اتاق')
    bedrooms = models.CharField(max_length=30,verbose_name='سالن')
    floor = models.CharField(max_length=30,verbose_name='طبقه')
    area = models.CharField(max_length=30)
    parking = models.CharField(max_length=30)
    # Address vila
    street = models.CharField(max_length=100,verbose_name='خیابان')
    city = models.CharField(max_length=50,verbose_name='شهر')
    state = models.CharField(max_length=20,verbose_name='کوچه')
    postal_code = models.CharField(max_length=10,verbose_name='پلاک')
    # slug
    slug = models.SlugField(unique=True,blank=True, null=True)
    # Single Property
    sing = models.ForeignKey(SingleProperty, null=True, blank=True, on_delete=models.CASCADE,
                             related_name='SingleProperty',verbose_name='')
    # Category
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.CASCADE, related_name='categories',verbose_name='دسته')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.title}'


class Contact(models.Model):
    fullname = models.CharField(max_length=100, verbose_name='نام شخص')
    email = models.EmailField(verbose_name='ایمیل')
    subject = models.CharField(max_length=100, verbose_name='موضوع')
    message = models.TextField(verbose_name='پیغام')
    date = models.DateTimeField(auto_now_add=True, null=True, blank=True, verbose_name='روز ارسال')

    def __str__(self):
        return f'{self.fullname} - {self.subject}'

properties/models.py
from django.db import models

class Visite(models.Model):
    email = models.EmailField()
    number = models.CharField(max_length=14, verbose_name='شماره تلفن')
    message = models.TextField(max_length=500,verbose_name='پیغام')
    subject = models.TextField(max_length=40, verbose_name='موضوع')
    full_name = models.CharField(verbose_name='نام شخص')
    title = models.CharField(null=True, blank=True ,max_length=100, verbose_name='ویلای مورد نظر')

    class Meta:
        verbose_name = "ملاقات"
        verbose_name_plural = "ملاقات ها"


    def __str__(self):
        return f'{self.number}: {self.full_name} {self.title}'

properties/forms.py
# from django import forms
# from .models import Visite
#
# class VisitForm(forms.ModelForm):
#     class Meta:
#         model = Visite
#         fields = ['title', 'email', 'number', 'subject', 'message']
#         widgets = {
#             'title': forms.TextInput(attrs={'class': 'form-control'}),
#             'email': forms.EmailInput(attrs={'class': 'form-control'}),
#             'number': forms.TextInput(attrs={'class': 'form-control'}),
#             'subject': forms.TextInput(attrs={'class': 'form-control'}),
#             'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
#         }

home/views.py
from django.shortcuts import render, redirect
from django.views.generic import  ListView
from django.views.generic.detail import DetailView
from home.models import *


class PropertiesView(ListView):
    queryset = Properties.objects.order_by('-id')[:3]
    context_object_name = 'properties'
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


def contact(request):
    if request.method == "POST":
        fullname = request.POST['fullname']
        email = request.POST['email']
        subject = request.POST['subject']
        message = request.POST['message']
        Contact.objects.create(fullname=fullname, email=email, subject=subject, message=message)
        return redirect('home:home')
    else:
        return render(request, 'home/index.html')


class PropertyDetailViews(DetailView):
    model = Properties
    context_object_name = 'details'
    template_name = 'home/detail.html'
    slug_url_kwarg = 'slug'

properties/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, View
from properties.models import *
from properties.forms import *
from home.models import *


class PropertiesByCategoryView(ListView):
    model = Properties
    template_name = 'properties/properties.html'
    context_object_name = 'properties'
    paginate_by = 6

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['category_id'])
        return Properties.objects.filter(category=self.category, category__active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        context['categorys'] = Category.objects.all()
        return context

class PropertiesView(ListView):
    model = Properties
    template_name = 'properties/properties.html'
    context_object_name = 'all_properties'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat'] = Category.objects.all()
        return context



class VisitCreateView(View):
    def get(self, request):
        title = request.GET.get('title')
        request.session['title'] = title
        return render(request, 'properties/contact.html', {'title': title})

    def post(self, request):
        title = request.session.get('title')
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        number = request.POST.get('number')
        message = request.POST.get('message')
        subject = request.POST.get('subject')
        Visite.objects.create(
            title=title,
            full_name=full_name,
            email=email,
            number=number,
            message=message,
            subject=subject)
        return redirect('home:home')

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}

{% block main %}

    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <span class="breadcrumb"><a href="#">Home</a>  /  Single Property</span>
                    <h3>Single Property</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="single-property section">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="main-image">
                        <img src="{% static 'images/single-property.jpg' %}" alt="">
                    </div>
                    <div class="main-content">

                        <span class="category">Apparment</span>
                        <h4>{{ details.street }}New Street {{ details.city }}, OR {{ details.postal_code }}</h4>
                        <p>{{ details.description }}</p>
                        <a class="btn btn-primary w-100" href="{% url 'properties:visit' %}?title={{ details.title}}">Visite</a>
                    </div>

                    <div class="accordion" id="accordionExample">
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingOne">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                    <a href="#">Best useful links ?</a>
                                </button>
                            </h2>
                            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    Dolor <strong>almesit amet</strong>, consectetur adipiscing elit, sed doesn't
                                    eiusmod tempor kinfolk tonx seitan crucifix 3 wolf moon bicycle rights keffiyeh
                                    snackwave wolf same vice, chillwave vexillologist incididunt ut labore consectetur
                                    <code>adipiscing</code> elit, sed do eiusmod tempor incididunt ut labore et dolore
                                    magna aliqua.
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingTwo">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                    How does this work ?
                                </button>
                            </h2>
                            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    Dolor <strong>almesit amet</strong>, consectetur adipiscing elit, sed doesn't
                                    eiusmod tempor kinfolk tonx seitan crucifix 3 wolf moon bicycle rights keffiyeh
                                    snackwave wolf same vice, chillwave vexillologist incididunt ut labore consectetur
                                    <code>adipiscing</code> elit, sed do eiusmod tempor incididunt ut labore et dolore
                                    magna aliqua.
                                </div>
                            </div>
                        </div>
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="headingThree">
                                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                        data-bs-target="#collapseThree" aria-expanded="false"
                                        aria-controls="collapseThree">
                                    Why is Villa the best ?
                                </button>
                            </h2>
                            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                                 data-bs-parent="#accordionExample">
                                <div class="accordion-body">
                                    Dolor <strong>almesit amet</strong>, consectetur adipiscing elit, sed doesn't
                                    eiusmod tempor kinfolk tonx seitan crucifix 3 wolf moon bicycle rights keffiyeh
                                    snackwave wolf same vice, chillwave vexillologist incididunt ut labore consectetur
                                    <code>adipiscing</code> elit, sed do eiusmod tempor incididunt ut labore et dolore
                                    magna aliqua.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="info-table">
                        <ul>
                            <li>
                                <img src="{% static 'images/info-icon-01.png' %}" alt="" style="max-width: 52px;">
                                <h4>{{ details.sing.total }}<br><span>Total Flat Space</span></h4>
                            </li>
                            <li>
                                <img src="{% static 'images/info-icon-02.png' %}" alt="" style="max-width: 52px;">
                                <h4>Contract<br><span>{{ details.sing.contract }}</span></h4>
                            </li>
                            <li>
                                <img src="{% static 'images/info-icon-03.png' %}" alt="" style="max-width: 52px;">
                                <h4>Payment<br><span>{{ details.sing.payment }}</span></h4>
                            </li>
                            <li>
                                <img src="{% static 'images/info-icon-04.png' %}" alt="" style="max-width: 52px;">
                                <h4>Safety<br><span>{{ details.sing.safety }}</span></h4>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="section best-deal">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="section-heading">
                        <h6>| Best Deal</h6>
                        <h2>Find Your Best Deal Right Now!</h2>
                    </div>
                </div>
                <div class="col-lg-12">
                    <div class="tabs-content">
                        <div class="row">
                            <div class="nav-wrapper ">
                                <ul class="nav nav-tabs" role="tablist">
                                    <li class="nav-item active" role="presentation">
                                        <button class="nav-link active" id="appartment-tab" data-bs-toggle="tab"
                                                data-bs-target="#appartment" type="button" role="tab"
                                                aria-controls="appartment"
                                                aria-selected="true"><a>{{ details.category.title }}</a>
                                        </button>
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-content" id="myTabContent">
                                <div class="tab-pane fade show active" id="appartment" role="tabpanel"
                                     aria-labelledby="appartment-tab">
                                    <div class="row">
                                        <div class="col-lg-3">
                                            <div class="info-table">
                                                <ul>
                                                    <li>Total Flat Space <span>{{ details.sing.total }}</span></li>
                                                    <li>Floor number <span>{{ details.floor }}</span></li>
                                                    <li>Number of rooms <span>{{ details.bathroom }}</span></li>
                                                    {% if details.sing.active_parking == True %}
                                                       <li>Parking Available <span>Yes</span></li>
                                                    {% else %}
                                                        <li>Parking Available <span>No</span></li>
                                                    {% endif %}
                                                    <li>Payment Process <span>{{ details.sing.payment }}</span></li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div class="col-lg-6">
                                            <img src="{% static 'images/deal-01.jpg' %}" alt="">
                                        </div>
                                        <div class="col-lg-3">
                                            <h4>All Info About {{ details.category.title }}</h4>
                                            <p>{{ details.about }}</p>
                                            <div class="icon-button">
                                                <a href="{% url 'properties:visit' %}"><i class="fa fa-calendar"></i> Schedule a visit</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

home/templates/home/messages.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body class="container py-5 bg-white bg-gradient">
    <h2 class="text-center text-primary bg-gradient">Your message was sent successfully</h2>
    <button class="btn btn-primary justify-content-center"><a class="text-dark" href="{% url 'home:home' %}">Back home</a></button>
    <hr>
</body>
</html>

properties/templates/properties/contact.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <span class="breadcrumb"><a href="#">Home</a>  / Visite</span>
                    <h3>Contact Us</h3>
                </div>
            </div>
        </div>
    </div>


    <div class="contact-page section">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="section-heading">
                        <h6>| Contact Us</h6>
                        <h2>Get In Touch With Our Agents</h2>
                    </div>
                    <p>When you really need to download free CSS templates, please remember our website TemplateMo.
                        Also, tell your friends about our website. Thank you for visiting. There is a variety of
                        Bootstrap HTML CSS templates on our website. If you need more information, please contact
                        us.</p>
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="item phone">
                                <img src="{% static 'images/phone-icon.png' %}" alt="" style="max-width: 52px;">
                                <h6>010-020-0340<br><span>Phone Number</span></h6>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="item email">
                                <img src="{% static 'images/email-icon.png' %}" alt="" style="max-width: 52px;">
                                <h6>info@villa.co<br><span>Business Email</span></h6>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <form id="contact-form" action="{% url 'properties:visit' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="col-lg-12">
                                    <fieldset>
                                        <label for="name">Full Name</label>
                                        <input type="text" name="full_name" id="name" placeholder="Your Name..."
                                               autocomplete="on"
                                               required>
                                    </fieldset>
                                </div>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <label for="email">Phone Address</label>
                                        <input type="text" name="number" id="email"
                                               placeholder="Your E-mail..." required="">
                                    </fieldset>
                                </div>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <label for="email">Email Address</label>
                                        <input type="text" name="email" id="email"
                                               placeholder="Your E-mail..." required="">
                                    </fieldset>
                                </div>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <label for="subject">Subject</label>
                                        <input type="subject" name="subject" id="subject" placeholder="Subject..."
                                               autocomplete="on">
                                    </fieldset>
                                </div>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <label for="message">Message</label>
                                        <textarea name="message" id="message" placeholder="Your Message"></textarea>
                                    </fieldset>
                                </div>
                                <div class="col-lg-12">
                                    <fieldset>
                                        <button type="submit" id="form-submit" class="orange-button">Send Message
                                        </button>
                                    </fieldset>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-lg-12">
                    <div id="map">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12469.776493332698!2d-80.14036379941481!3d25.907788681148624!2m3!1f357.26927939317244!2f20.870722720054623!3f0!3m2!1i1024!2i768!4f35!3m3!1m2!1s0x88d9add4b4ac788f%3A0xe77469d09480fcdb!2sSunny%20Isles%20Beach!5e1!3m2!1sen!2sth!4v1642869952544!5m2!1sen!2sth"
                                width="100%" height="500px" frameborder="0"
                                style="border:0; border-radius: 10px; box-shadow: 0px 0px 15px rgba(0, 0, 0, 0.15);"
                                allowfullscreen=""></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

properties/templates/properties/properties.html
{% extends 'base.html' %}
{% load static %}
{% block main %}

    <div class="page-heading header-text">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <span class="breadcrumb"><a href="#">Home</a> / Properties</span>
                    <h3>Properties</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="section properties">
        <div class="container">
            <ul class="properties-filter">
                {% for cat in categorys %}
                    <li>
                        <a class="btn"
                           href="{% url 'properties:products' cat.id %}"
                           data-filter="*">{{ cat.title }}</a>
                    </li>
                {% endfor %}
                {% for category in cat %}
                    <li>
                        <a class="btn"
                           href="{% url 'properties:products' category.id %}"
                           data-filter="*">{{ category.title }}</a>
                    </li>
                {% endfor %}
                <li>
                    <a class="btn"
                       href="{% url 'properties:property_list' %}"
                       data-filter="*">All</a>
                </li>
            </ul>
            <div class="row properties-box">
                {% for product in all_properties %}
                    <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 adv">
                        <div class="item">
                            <a href="{% url 'home:detail' product.id %}"><img
                                    src="{{ product.image.url }}" alt=""></a>
                            <span class="category">Luxury Villa</span>
                            <h6>${{ product.price }}</h6>
                            <h4><a href="{% url 'home:detail' product.id %}">{{ product.street }}New
                                Street {{ product.city }}, OR {{ product.postal_code }}</a></h4>
                            <ul>
                                <li>Bedrooms: <span>{{ product.bedrooms }}</span></li>
                                <li>Bathrooms: <span>{{ product.bathroom }}</span></li>
                                <li>Area: <span>{{ product.area }}</span></li>
                                <li>Floor: <span>{{ product.floor }}</span></li>
                                <li>Parking: <span>{{ product.parking }} spots</span></li>
                            </ul>
                            <div class="main-button">
                                <a href="{% url 'properties:visit' %}?{{ product.title }}">Schedule a visit</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row properties-box">
                {% for product in properties %}
                    <div class="col-lg-4 col-md-6 align-self-center mb-30 properties-items col-md-6 adv">
                        <div class="item">
                            <a href="{% url 'home:detail' product.id %}"><img
                                    src="{{ product.image.url }}" alt=""></a>
                            <span class="category">Luxury Villa</span>
                            <h6>${{ product.price }}</h6>
                            <h4><a href="{% url 'home:detail' product.id %}">{{ product.street }}New
                                Street {{ product.city }}, OR {{ product.postal_code }}</a></h4>
                            <ul>
                                <li>Bedrooms: <span>{{ product.bedrooms }}</span></li>
                                <li>Bathrooms: <span>{{ product.bathroom }}</span></li>
                                <li>Area: <span>{{ product.area }}</span></li>
                                <li>Floor: <span>{{ product.floor }}</span></li>
                                <li>Parking: <span>{{ product.parking }} spots</span></li>
                            </ul>
                            <div class="main-button">
                                <a href="{% url 'properties:visit' %}?{{ product.title }}">Schedule a visit</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <ul class="pagination">
                        {% if properties.has_previous %}
                            <li><a href="?page={{ properties.previous_page_number }}">«</a></li>
                        {% endif %}

                        {% for num in properties.paginator.page_range %}
                            {% if num == properties.number %}
                                <li class="active"><span>{{ num }}</span></li>
                            {% else %}
                                <li><a href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        {% if properties.has_next %}
                            <li><a href="?page={{ properties.next_page_number }}">»</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/include/header_area_start.html
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="{% url 'home:home' %}" class="logo">
                        <h1>Villa</h1>
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{% url 'home:home' %}" class="active">Home</a></li>
                        <li><a href="{% url 'properties:property_list' %}">Properties</a></li>
                        <li><a href="{% url 'properties:visit' %}">Visite Us</a></li>
                        <li><a href="#"><i class="fa fa-calendar"></i> Schedule a visit</a></li>
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>